# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */ #
# Window Rules - Hyprland 0.53+ Correct Syntax

# Workspace 1: Taner (Personal)
windowrule = workspace 1, match:class ^(waterfox)$
windowrule = workspace 1, match:title .*Personal.*

# Workspace 2: Work
windowrule = workspace 2, match:class ^(waterfox)$
windowrule = workspace 2, match:title .*Original profile.*

# Workspace 3: WhatsApp
windowrule = workspace 3, match:class ^(waterfox)$
windowrule = workspace 3, match:title .*WhatsApp.*

# Workspace 5: Thunderbird
windowrule = workspace 5, match:class ^(net.thunderbird.Thunderbird)$

# Workspace 5: TÜRKINFORM
# windowrule = workspace 5, match:class ^(waterfox)$
windowrule = workspace 5, match:title .*TÜRKINFORM.*

# Workspace 6: Ghostty
windowrule = workspace 6, match:class ^(com.mitchellh.ghostty)$

# Workspace 7: Okular
windowrule = workspace 7, match:class ^(org.kde.okular)$

# --- GNOME Loupe ---
windowrule = opacity 1.0 override 1.0 override, match:class ^(org.gnome.Loupe)$
windowrule = float on, match:class ^(org.gnome.Loupe)$
windowrule = size 60% 60%, match:class ^(org.gnome.Loupe)$
windowrule = center on, match:class ^(org.gnome.Loupe)$

# --- Mousepad ---
windowrule = float on, match:class ^(mousepad)$
windowrule = center on, match:class ^(mousepad)$
windowrule = size 800 500, match:class ^(mousepad)$
windowrule = opacity 0.95 override 0.85 override, match:class ^(mousepad)$
windowrule = pin on, match:class ^(mousepad)$
