
# /* ---- 💫 JaKooLit Dotfiles - Düzenlenmiş 💫 ---- */ 

# 1. HOSTNAME TANIMLAMA (En Üstte Kalsın)
$host = $(hostname)

# 2. DIŞ DOSYALARI ÇAĞIRMA
$configs = $HOME/.config/hypr/configs
$UserConfigs = $HOME/.config/hypr/UserConfigs

# Temel Sistem Ayarları
source= $configs/Startup_Apps.conf 
source= $UserConfigs/Startup_Apps.conf
source= $configs/ENVariables.conf
source= $UserConfigs/ENVariables.conf
source= $configs/Laptops.conf 
source= $UserConfigs/Laptops.conf 
source= $configs/WindowRules.conf
source= $UserConfigs/WindowRules.conf
source= $configs/SystemSettings.conf
source= $UserConfigs/UserDecorations.conf
source= $UserConfigs/UserAnimations.conf
source= $UserConfigs/UserKeybinds.conf
source= $UserConfigs/UserSettings.conf
source= $UserConfigs/01-UserDefaults.conf
source= $configs/Keybinds.conf

# --- KRİTİK BÖLÜM: DİNAMİK MONİTÖ wR VE WORKSPACE ---
# Buradaki eski 'source=...monitors.conf' satırlarını sildik.
# Yerine bilgisayar adına göre otomatik yükleme yapıyoruz.
#source = ~/.config/hypr/monitors_$(hostname).conf
# Dinamik olarak hostname'i bulur ve o konfigürasyonu enjekte eder
# 3. GENEL PERFORMANS VE GÖRSEL AYARLAR (Temizlendi)
misc {
    vfr = true
    vrr = 0
}

animations {
    enabled = false # CPU dostu
}

decoration {
    blur {
        enabled = false
    }
    active_opacity = 1.0
    inactive_opacity = 1.0
}

general {
    allow_tearing = false
    border_size = 3
    col.active_border = rgba(ff0000ff)   # Kırmızı
    col.inactive_border = rgba(0000ffff) # Mavi
}

# 4. ÖZEL PENCERE KURALLARI
windowrulev2 = workspace 5, class:^(net\.thunderbird\.Thunderbird)$
windowrulev2 = workspace 6, class:^(com.mitchellh.ghostty)$

# 5. SERVİSLER
exec-once = wl-paste --type text --watch cliphist store -max-items 500
exec-once = wl-paste --type image --watch cliphist store -max-items 100
#source = ~/.config/hypr/monitors_fedora.conf
#source = ~/.config/hypr/monitors_$host.conf
exec-once = ln -sf ~/.config/hypr/monitors_$(hostname).conf ~/.config/hypr/monitors_active.conf
source = ~/.config/hypr/monitors_active.conf
