# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */ #
# Taner Orak - Hypridle Optimize Edilmiş Yapılandırma

$iDIR="$HOME/.config/swaync/images/ja.png"

general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# 1. Aşama: Uyarı (9. dakika)
listener {
    timeout = 540
    on-timeout = notify-send -i $iDIR "Boşta kaldınız!"
    on-resume = notify-send -i $iDIR "Hoş geldiniz!"
}

# 2. Aşama: Kilitleme ve Ekranı Kapatma (10. dakika)
# Kilitlendiği an ekran sinyalini keser
listener {
    timeout = 600
    on-timeout = hyprlock && hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}

# 3. Aşama: Kilit Ekranı Güç Tasarrufu
# Eğer manuel kilitlediysen (Super+L gibi), 5 saniye sonra ekranı kapatır
listener {
    timeout = 5
    on-timeout = pidof hyprlock && hyprctl dispatch dpms off
    on-resume = sleep 1 && hyprctl dispatch dpms on
}
