# Lenovo (Soldaki monitör - Başlangıç noktası 0x0)
monitor = DP-3, 1920x1080@100, 0x0, 1

# Samsung (Sağdaki monitör - Lenovo'nun bittiği yer olan 1920x0)
monitor = HDMI-A-1, 1920x1080@60, 1920x0, 1
# --- 🖥️ WORKSPACE ATAMALARI ---

# Lenovo (Sol Monitör - DP-3) için 1'den 5'e kadar
workspace = 1, monitor:DP-3, default:true
workspace = 2, monitor:DP-3
workspace = 3, monitor:DP-3
workspace = 4, monitor:DP-3
workspace = 5, monitor:DP-3

# Samsung (Sağ Monitör - HDMI-A-1) için 6'dan 10'a kadar
workspace = 6, monitor:HDMI-A-1, default:true
workspace = 7, monitor:HDMI-A-1
workspace = 8, monitor:HDMI-A-1
workspace = 9, monitor:HDMI-A-1
workspace = 10, monitor:HDMI-A-1
