# =================================================================
# MONİTÖR KONUMLANDIRMALARI (Kesin Çözüm)
# =================================================================

# Laptop Ekranı Tamamen Kapalı
# monitor = eDP-1, disable

# 1. Sol Taraf (DVI/HDMI bağlı olan ASUS - DP-2) - 0x0 noktasında başlar

# 2. Sağ Taraf (VGA bağlı olan ASUS - DP-5) - Soldakinin bitişiğinde (1920x0) başlar
monitor = DP-6, 1920x1080@60, 0x0, 1
monitor = DP-2, 1920x1080@60, 1920x0, 1

# =================================================================
# WORKSPACE TANIMLAMALARI (Masaüstü Düzeni)
# =================================================================

# Sol Ekran (DP-2) için Workspace 1'den 5'e kadar
workspace = 1, monitor:DP-6, default:true
workspace = 2, monitor:DP-6
workspace = 3, monitor:DP-6
workspace = 4, monitor:DP-6
workspace = 5, monitor:DP-6

# Sağ Ekran (DP-5) için Workspace 6'dan 10'a kadar
workspace = 6, monitor:DP-2, default:true
workspace = 7, monitor:DP-2
workspace = 8, monitor:DP-2
workspace = 9, monitor:DP-2
workspace = 10, monitor:DP-2
