# DP-3 (Lenovo/LG - Sol Monitör) için 1'den 5'e kadar
workspace = 1, monitor:DP-3, default:true
workspace = 2, monitor:DP-3
workspace = 3, monitor:DP-3
workspace = 4, monitor:DP-3
workspace = 5, monitor:DP-3

# HDMI-A-1 (Samsung - Sağ Monitör) için 6'dan 10'a kadar
workspace = 6, monitor:HDMI-A-1, default:true
workspace = 7, monitor:HDMI-A-1
workspace = 8, monitor:HDMI-A-1
workspace = 9, monitor:HDMI-A-1
workspace = 10, monitor:HDMI-A-1

# Monitör Pozisyon Ayarları
# Sol monitör (DP-3) 0x0 koordinatında, sağdaki (HDMI-A-1) onun bitiminde (1920x0) başlar.
monitor = DP-3, 1920x1080@60, 0x0, 1
monitor = HDMI-A-1, 1920x1080@60, 1920x0, 1
