# =================================================================
# MONİTÖR KONUMLANDIRMALARI
# =================================================================
# Laptop Ekranı Tamamen Kapalı
monitor = eDP-1, disable

# Sol Taraf (DP-2) - DVI/HDMI bağlı ASUS - 0x0'dan başlar
monitor = DP-5, 1920x1080@60, 0x0, 1

# Sağ Taraf (DP-5) - VGA/dock bağlı ASUS - 1920x0'dan başlar
monitor = DP-2, 1920x1080@60, 1920x0, 1

# =================================================================
# WORKSPACE TANIMLAMALARI
# =================================================================
# Sol ekran (DP-2) → 1-5
workspace = 1, monitor:DP-5, default:true
workspace = 2, monitor:DP-5
workspace = 3, monitor:DP-5
workspace = 4, monitor:DP-5
workspace = 5, monitor:DP-5

# Sağ ekran (DP-5) → 6-10
workspace = 6, monitor:DP-2, default:true
workspace = 7, monitor:DP-2
workspace = 8, monitor:DP-2
workspace = 9, monitor:DP-2
workspace = 10, monitor:DP-2
