# =================================================================
# MONİTÖR KONUMLANDIRMALARI (En Basit Port Mantığı)
# =================================================================

# Laptop Ekranı Tamamen Devre Dışı
monitor = eDP-1, disable

# SOL EKRAN (Eğer yönü ters olursa buradaki DP-2'yi DP-5 yap)
monitor = DP-2, 1920x1080@60, 0x0, 1

# SAĞ EKRAN (Eğer yönü ters olursa buradaki DP-5'i DP-2 yap)
monitor = DP-5, 1920x1080@60, 1920x0, 1


# =================================================================
# WORKSPACE TANIMLAMALARI (Port İsimlerine Göre Masaüstleri)
# =================================================================

# Sol Ekran için Workspace 1'den 5'e kadar
workspace = 1, monitor:DP-2, default:true
workspace = 2, monitor:DP-2
workspace = 3, monitor:DP-2
workspace = 4, monitor:DP-2
workspace = 5, monitor:DP-2

# Sağ Ekran için Workspace 6'dan 10'a kadar
workspace = 6, monitor:DP-5, default:true
workspace = 7, monitor:DP-5
workspace = 8, monitor:DP-5
workspace = 9, monitor:DP-5
workspace = 10, monitor:DP-5
