# =================================================================
# MONİTÖR KONUMLANDIRMALARI
# =================================================================
monitor = eDP-1, disable

# Sol monitör
monitor = desc:Ancor Communications Inc ASUS VS228 F7LMTF098666, 1920x1080@60, 0x0, 1

# Sağ monitör
monitor = desc:Ancor Communications Inc ASUS VS228 E7LMTF193542, 1920x1080@60, 1920x0, 1

# Fallback
monitor = ,preferred,auto,1

# =================================================================
# WORKSPACE TANIMLAMALARI
# =================================================================
workspace = 1, monitor:desc:Ancor Communications Inc ASUS VS228 F7LMTF098666, default:true
workspace = 2, monitor:desc:Ancor Communications Inc ASUS VS228 F7LMTF098666
workspace = 3, monitor:desc:Ancor Communications Inc ASUS VS228 F7LMTF098666
workspace = 4, monitor:desc:Ancor Communications Inc ASUS VS228 F7LMTF098666
workspace = 5, monitor:desc:Ancor Communications Inc ASUS VS228 F7LMTF098666

workspace = 6, monitor:desc:Ancor Communications Inc ASUS VS228 E7LMTF193542, default:true
workspace = 7, monitor:desc:Ancor Communications Inc ASUS VS228 E7LMTF193542
workspace = 8, monitor:desc:Ancor Communications Inc ASUS VS228 E7LMTF193542
workspace = 9, monitor:desc:Ancor Communications Inc ASUS VS228 E7LMTF193542
workspace = 10, monitor:desc:Ancor Communications Inc ASUS VS228 E7LMTF193542
