# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(141515)
$foreground = rgb(E4E5E2)
$color0 = rgb(3B3C3D)
$color1 = rgb(0D1012)
$color2 = rgb(0D1012)
$color3 = rgb(343828)
$color4 = rgb(41555F)
$color5 = rgb(6D6D35)
$color6 = rgb(868780)
$color7 = rgb(D1D1CD)
$color8 = rgb(92928F)
$color9 = rgb(111518)
$color10 = rgb(111518)
$color11 = rgb(464B36)
$color12 = rgb(57717F)
$color13 = rgb(919146)
$color14 = rgb(B3B4AB)
$color15 = rgb(D1D1CD)
