# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(050019)
$foreground = rgb(F6F0F3)
$color0 = rgb(050019)
$color1 = rgb(16247E)
$color2 = rgb(16247E)
$color3 = rgb(16247E)
$color4 = rgb(5355A6)
$color5 = rgb(836EA3)
$color6 = rgb(AC9EA5)
$color7 = rgb(EAE1E5)
$color8 = rgb(A39DA0)
$color9 = rgb(1E30A8)
$color10 = rgb(1E30A8)
$color11 = rgb(1E30A8)
$color12 = rgb(6F71DD)
$color13 = rgb(AE93D9)
$color14 = rgb(E5D3DC)
$color15 = rgb(EAE1E5)
