# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(171819)
$foreground = rgb(FAEED6)
$color0 = rgb(3E3F40)
$color1 = rgb(101216)
$color2 = rgb(373F4C)
$color3 = rgb(A8474C)
$color4 = rgb(589576)
$color5 = rgb(888E97)
$color6 = rgb(B59B67)
$color7 = rgb(F0DFBC)
$color8 = rgb(A89C84)
$color9 = rgb(15181D)
$color10 = rgb(4A5465)
$color11 = rgb(E05F65)
$color12 = rgb(76C79D)
$color13 = rgb(B5BDC9)
$color14 = rgb(F1CF8A)
$color15 = rgb(F0DFBC)
